// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbbtB4yOrBP7Vx0PAgqfMrJEhTmRIRW7A',
    appId: '1:523636065584:web:3f1fe59addeda024d8f4f5',
    messagingSenderId: '523636065584',
    projectId: 'movie-g5',
    authDomain: 'movie-g5.firebaseapp.com',
    storageBucket: 'movie-g5.firebasestorage.app',
    measurementId: 'G-T1DTVGGG2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPFSgDVSRqDVosQUQLpDHrCDQepnQCfo',
    appId: '1:523636065584:android:b3dd82d583fa1414d8f4f5',
    messagingSenderId: '523636065584',
    projectId: 'movie-g5',
    storageBucket: 'movie-g5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiFF8aFQnt85WpKM1EPQPYCQvRgUr9798',
    appId: '1:523636065584:ios:34e59a6db0887468d8f4f5',
    messagingSenderId: '523636065584',
    projectId: 'movie-g5',
    storageBucket: 'movie-g5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiFF8aFQnt85WpKM1EPQPYCQvRgUr9798',
    appId: '1:523636065584:ios:34e59a6db0887468d8f4f5',
    messagingSenderId: '523636065584',
    projectId: 'movie-g5',
    storageBucket: 'movie-g5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbbtB4yOrBP7Vx0PAgqfMrJEhTmRIRW7A',
    appId: '1:523636065584:web:6ff68c78beb5d1b5d8f4f5',
    messagingSenderId: '523636065584',
    projectId: 'movie-g5',
    authDomain: 'movie-g5.firebaseapp.com',
    storageBucket: 'movie-g5.firebasestorage.app',
    measurementId: 'G-W3WB4CQCR7',
  );
}
